//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayerT.DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_PayrollOfflineDataIssueList
    {
        public int ID { get; set; }
        public string TITLE { get; set; }
        public string FIRST_NAME { get; set; }
        public string SURNAME { get; set; }
        public Nullable<double> LOAN_AMOUNT { get; set; }
        public Nullable<double> NET_MONTHLY_INCOME { get; set; }
        public Nullable<double> TENURE { get; set; }
        public Nullable<double> EXISTING_LOAN_TENURE_LEFT { get; set; }
        public Nullable<double> EXISTING_LOAN_AMOUNT { get; set; }
        public string ANY_EXISTING_LOAN { get; set; }
        public string MOBILE_NUMBER { get; set; }
        public string HOME_ADDRESS { get; set; }
        public string BANK_VERIFICATION_NUMBER { get; set; }
        public string MEANS_OF_ID { get; set; }
        public string IDENTIFICATION_NUMBER { get; set; }
        public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }
        public string PERSONAL_EMAIL { get; set; }
        public string LANDMARK { get; set; }
        public string CLOSEST_BUSTOP { get; set; }
        public string LGA { get; set; }
        public string STATE_OF_RESIDENCE { get; set; }
        public string ACCOMMODATION_TYPE { get; set; }
        public string ORGANISATION_CLOSEST_BUSTOP { get; set; }
        public string ORGANISATION_LANDMARK { get; set; }
        public string EMPLOYER { get; set; }
        public string OCCUPATION { get; set; }
        public string DESIGNATION { get; set; }
        public string EMPLOYEE_ID { get; set; }
        public string EMPLOYMENT_STATUS { get; set; }
        public string DEPARTMENT { get; set; }
        public string EMAIL { get; set; }
        public Nullable<double> LENGTH_OF_SERVICE_YEARS { get; set; }
        public Nullable<double> LENGTH_OF_SERVICE_MONTHS { get; set; }
        public string NOK_NAME { get; set; }
        public string NOK_RELATIONSHIP { get; set; }
        public string NOK_HOME_ADDRESS { get; set; }
        public string NOK_PHONE { get; set; }
        public string NOK_EMAIL_ADDRESS { get; set; }
        public string GENDER { get; set; }
        public string MARITAL_STATUS { get; set; }
        public string BANK_NAME { get; set; }
        public string ACCOUNT_NUMBER { get; set; }
        public string ACCOUNT_NAME { get; set; }
        public string INSTITUTION { get; set; }
        public string GUARANTOR_SURNAME { get; set; }
        public string GUARANTOR_OTHERNAMES { get; set; }
        public string GUARANTOR_CONTACT_ADDRESS { get; set; }
        public string GUARANTOR_PHONE_NUMBER { get; set; }
        public string GUARANTOR_RELATIONSHIP { get; set; }
        public string GUARANTOR_EMAIL_ADDRESS { get; set; }
        public string REPAYMENT_METHOD { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> DISBURSEMENT_DATE { get; set; }
        public Nullable<double> FIRST_MONTH_PAYMENT { get; set; }
        public string PAID { get; set; }
        public Nullable<double> SECONDMONTHPAYMENT { get; set; }
        public Nullable<double> THIRDMONTHPAYMENT { get; set; }
        public Nullable<double> FOURTHMONTHPAYMENT { get; set; }
        public Nullable<double> FIFTHMONTHPAYMENT { get; set; }
        public Nullable<double> SIXTHMONTHPAYMENT { get; set; }
        public Nullable<double> SEVENTHMONTHPAYMENT { get; set; }
        public Nullable<double> EIGHTHMONTHPAYMENT { get; set; }
        public Nullable<double> NINETHMONTHPAYMENT { get; set; }
        public Nullable<double> TENTHMONTHPAYMENT { get; set; }
        public Nullable<double> ELEVENTHMONTHPAYMENT { get; set; }
        public Nullable<double> TWELVETHMONTHPAYMENT { get; set; }
        public Nullable<double> PERIOD_OF_REPAYMENT { get; set; }
        public string DEFAULT { get; set; }
        public string PRORATED_AMOUNT { get; set; }
        public string RemitaBankCode { get; set; }
        public string BankCode { get; set; }
        public string LoanRefNumber { get; set; }
        public Nullable<int> Institution_FK { get; set; }
    }
}
