//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayerT.DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_PILGRIMS_MULTIPLE_AMOUNT_EDIT_OLD
    {
        public int ID { get; set; }
        public string LoanRefNumber { get; set; }
        public Nullable<double> SN { get; set; }
        public string TITLE { get; set; }
        public string FIRSTNAME { get; set; }
        public string SURNAME { get; set; }
        public Nullable<double> LOANAMOUNT { get; set; }
        public Nullable<double> NETMONTHLYINCOME { get; set; }
        public Nullable<double> TENURE { get; set; }
        public Nullable<double> EXISTINGLOANTENURELEFT { get; set; }
        public Nullable<double> EXISTINGLOANAMOUNT { get; set; }
        public string ANYEXISTINGLOAN { get; set; }
        public Nullable<double> MOBILENUMBER { get; set; }
        public string HOMEADDRESS { get; set; }
        public Nullable<double> BANKVERIFICATIONNUMBER { get; set; }
        public string MEANSOFID { get; set; }
        public Nullable<double> IDENTIFICATIONNUMBER { get; set; }
        public Nullable<double> DATEOFBIRTH { get; set; }
        public string PERSONALEMAIL { get; set; }
        public string LANDMARK { get; set; }
        public string CLOSESTBUSTOP { get; set; }
        public string LGA { get; set; }
        public string STATEOFRESIDENCE { get; set; }
        public string ACCOMMODATIONTYPE { get; set; }
        public string ORGANISATIONCLOSESTBUSTOP { get; set; }
        public string ORGANISATIONLANDMARK { get; set; }
        public string EMPLOYER { get; set; }
        public string OCCUPATION { get; set; }
        public string DESIGNATION { get; set; }
        public string EMPLOYEEID { get; set; }
        public string EMPLOYMENTSTATUS { get; set; }
        public string DEPARTMENT { get; set; }
        public string EMAIL { get; set; }
        public Nullable<double> LENGTHOFSERVICEYEARS { get; set; }
        public Nullable<double> LENGTHOFSERVICEMONTHS { get; set; }
        public string NOK_NAME { get; set; }
        public string NOK_RELATIONSHIP { get; set; }
        public string NOK_HOMEADDRESS { get; set; }
        public Nullable<double> NOK_PHONE { get; set; }
        public string NOK_EMAILADDRESS { get; set; }
        public string GENDER { get; set; }
        public string MARITAL_STATUS { get; set; }
        public string BANKNAME { get; set; }
        public Nullable<double> ACCOUNTNUMBER { get; set; }
        public string ACCOUNTNAME { get; set; }
        public string INSTITUTION { get; set; }
        public string GUARANTORSURNAME { get; set; }
        public string GUARANTOROTHERNAMES { get; set; }
        public string GUARANTOR_CONTACT_ADDRESS { get; set; }
        public Nullable<double> GUARANTOR_PHONE_NUMBER { get; set; }
        public string GUARANTOR_RELATIONSHIP { get; set; }
        public string GUARANTOR_EMAIL_ADDRESS { get; set; }
        public string REPAYMENT_METHOD { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> DISBURSEMENTDATE { get; set; }
        public Nullable<double> FIRSTMONTHPAYMENT { get; set; }
        public string PAID { get; set; }
        public Nullable<double> MONTHLYPAYMENTAMOUNT { get; set; }
        public Nullable<double> NOOFMONTHSPAID { get; set; }
        public string DEFAULT { get; set; }
        public string MONTH_1___JUNE_2019 { get; set; }
        public Nullable<double> MONTH_2____JULY_2019 { get; set; }
        public Nullable<double> MONTH_3______AUG_2019 { get; set; }
        public Nullable<double> MONTH_4___________SEPT_2019 { get; set; }
        public Nullable<double> MONTH_5_____________OCT_2019 { get; set; }
        public Nullable<double> MONTH_6___________________NOV_2019 { get; set; }
        public Nullable<double> MONTH_7__________________DEC_2019 { get; set; }
        public Nullable<double> MONTH_8____________________JAN_2020 { get; set; }
        public Nullable<double> MONTH_9_______________________FEB_2020 { get; set; }
        public Nullable<double> MONTH_10______________________MAR_2020 { get; set; }
        public Nullable<double> MONTH_11___APR_2020 { get; set; }
        public Nullable<double> MONTH_12______MAY_2020 { get; set; }
        public Nullable<double> MONTH_13_____JUNE_2020 { get; set; }
        public string MONTH_14____JULY_2020 { get; set; }
        public string MONTH_15____AUG_2021 { get; set; }
        public string MONTH_14____JULY_2021 { get; set; }
        public string MONTH_13_____JUNE_2022 { get; set; }
        public string MONTH_14____JULY_2022 { get; set; }
        public string MONTH_16_SEPT_2020 { get; set; }
        public string MONTH_17_OCT_2020 { get; set; }
    }
}
