//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayerT.DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class NYSCLoanSetUp
    {
        public int ID { get; set; }
        public Nullable<int> Tenure { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> Repayments { get; set; }
        public Nullable<double> ManagementFee { get; set; }
        public Nullable<double> Repayment { get; set; }
        public Nullable<double> MonthlyInterest { get; set; }
        public Nullable<double> MonthlyInterestAmount { get; set; }
        public Nullable<int> IsVisible { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
    }
}
